No more .debs
Moved from .deb packages to simple tarballs. Not quite complete yet.

diff --git a/usr/bin/sysupdate/sysupdate b/usr/bin/sysupdate/sysupdate
--- a/usr/bin/sysupdate/sysupdate
+++ b/usr/bin/sysupdate/sysupdate
@@ -1,5 +1,27 @@
 #!/bin/ksh
 
+# sysupdate: update Ragnarok base system.
+#
+# $Id: sysupdate,v 1.1 2023/08/15 15:46:04 lecorbeau Exp $
+#
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+#											#
+#	Copyright (c) 2022, Ian LeCorbeau <I-LeCorbeau (at) protonmail (dot) com>	#
+#											#
+#	Permission to use, copy, modify, and/or distribute this software for any	#
+#	purpose with or without fee is hereby granted, provided that the above		#
+#	copyright notice and this permission notice appear in all copies.		#
+#											#
+#	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES	#
+#	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF		#
+#	MERCHANTABILITY AND FITNESS IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR		#
+#	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES		#
+#	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN		#
+#	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF		#
+#	OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.			#
+#											#
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+
 . /lib/ragnarok-shlib
 
 set -e
@@ -82,11 +104,73 @@ check_update() {
 	fi
 }
 
-# extract patch tarball then install it
-install_pkg() {
-	local _pkg=$1
+# Create a backup tarball
+# Don't overcomplicate things. Any directory in rollback is a backup
+# so just archive them.
+create_backup() {
+	local _bdir _dir=$1 _rc=0
 
-	dpkg -i "$TMP"/"$_pkg"
+	_bdir="/var/db/updates"
+
+	cd "$_bdir" && \
+		handle_tar -c "${_dir}.old.tgz" "${_dir}" || rc=$? && \
+		rm -r "${_dir}"
+	cd ..
+
+	if ((_rc != 0)); then
+		printf '%s\n' "Failed to create rollback for ${_dir}."
+	fi
+}
+
+# Extract or create tarball
+handle_tar() {
+	local _arc=$2 _opts
+
+	case "$1" in
+		-e)	_opts="-xpzf"
+			;;
+		-c)	_opts="-cpzf"
+	esac
+	shift
+	bsdtar --xattrs "$_opts" "$@"
+}
+
+# Install the updated files, preserving their permissions, and create
+# backup files for rollback.
+install_files() {
+	local _dir=$1 _files _perms _ret=0 _u
+
+	_files=$(find "$_dir" -type f)
+
+	for _file in ${_files}; do
+		_perms=$(stat -c "-m %a -g %g -o %G" "${_file}")
+		_u=${_file##${_dir}}
+
+		/usr/bin/install ${_perms} -b --suffix=".old" -t "$(dirname ${_u})" \
+			"${_file}" || _ret=$?
+	done
+
+	if ((_ret != 0)); then
+		printf '%s\n' "Failed to install ${_file}."
+	fi
+}
+
+# Move the backup files to rollback dir.
+mv_old() {
+	local _bdir _dir=$1 _files _ret=0 _u
+
+	_bdir="/var/db/updates"
+	_files=$(find "$_dir" -type f)
+
+	for _file in ${_files}; do
+		_u=${_file##${_dir}}
+		mkdir -p "${_bdir}/$(dirname ${_file##*_})"
+		mv -- "${_u}.old" "${_bdir}/$(dirname ${_file##*_}/${_u##*/})" || _ret=$?
+	done
+
+	if ((_ret != 0)); then
+		printf '%s\n' "Failed to move ${_u}.old"
+	fi
 }
 
 do_update() {
@@ -101,23 +185,27 @@ do_update() {
 	set -A _patches -- $(comm -1 -3 --output-delimiter="" /var/db/updates/sysupdate.list "${TMP}/sysupdate.list")
 	printf '%s\n' "Downloading updates..." &&
 	for patch in "${_patches[@]}"; do
-		get_upd "${patch}"
-		get_upd "${patch}.sig"
+		get_upd "${patch}.tgz"
+		get_upd "${patch}.tgz.sig"
 	done
 
 	for patch in "${_patches[@]}"; do
 		printf '%s\n' "Verifying $patch signature"
-		check_sig "${patch}"
+		check_sig "${patch}.tgz"
 		printf '%s\n' "Installing ${patch}..."
-		install_pkg "${patch}"
+		handle_tar -e "${TMP}/${patch}.tgz" -C "${TMP}"
+		install_files "${TMP}/${patch}"
+		mv_old "${TMP}/${patch}"
+		printf '%s\n' "Creating rollback for ${patch##*_}..."
+		create_backup "${patch##*_}"
 	done
-
+	
 	# Copy the new sysupdate list to /var/db
 	printf '%s\n' "Updating /var/db/updates/sysupdate.list..."
 	unpriv "cat /var/db/updates/sysupdate.list > /var/db/updates/sysupdate.list.old"
 	cp "${TMP}"/sysupdate.list /var/db/updates/
 	# Make sure the new list is owned by the _sysupdate user
-	chown _sysupdate /var/db/updates/sysupdate.list
+	chown _sysupdate:_sysupdate /var/db/updates/sysupdate.list
 
 	exit 0
 }
@@ -130,17 +218,17 @@ do_download() {
 
 	_pkg=$(grep "$1" "${TMP}/sysupdate.list")
 
-	get_upd "${_pkg}"
-	get_upd "${_pkg}.sig"
+	get_upd "${_pkg}.tgz"
+	get_upd "${_pkg}.tgz.sig"
 
 	# move package to /var/db/updates
-	unpriv "cp ${TMP}/${_pkg} /var/db/updates/"
-	unpriv "cp ${TMP}/${_pkg}.sig /var/db/updates/"
+	unpriv "cp ${TMP}/${_pkg}.tgz /var/db/updates/"
+	unpriv "cp ${TMP}/${_pkg}.tgz.sig /var/db/updates/"
 }
 
 # List installed update
 do_list() {
-	printf '%s\n' "The following updates are installed"
+	printf '%s\n' "The following updates are installed:"
 	cat /var/db/updates/sysupdate.list
 }
 
@@ -161,19 +249,17 @@ $(comm -1 -3 --output-delimiter="" "/var/db/updates/sysupdate.list" "${TMP}/sysu
 # Downgrade if an update caused an issue. Untested yet.
 # Not tested yet
 do_revert() {
-	local _update _pkg=$1
+	local _upd=$1
 
-	_update=$(grep "$_pkg" "/var/db/updates/sysupdate.list.old")
+	echo "${TMP}"
+	unpriv -f "${TMP}/${_upd}.old.tgz" "cp /var/db/updates/${_upd}.old.tgz ${TMP}/"
 
-	printf '%s\n' "Downloading update and signature..."
-	get_upd "${_update}"
-	get_upd "${_update}.sig"
-	
-	printf '%s\n' "Verifying $_update signature..."
-	check_sig "${_update}"
-
-	printf '%s\n' "Installing update..."
-	install_pkg "${_update}"
+	# Install the files. Keep the .old files where they are, which will allow them to be
+	# tested and/or inspected further by the user. They will get removed once the faulty
+	# update gets fixed.
+	handle_tar -e "${TMP}/${_upd}.old.tgz" -C "${TMP}"
+	printf '%s\n' "Reverting ${_upd##*_}"
+	install_files "${TMP}/${_upd}"
 }
 
 # Cleanup after finish
